(function(){
  const PROFILE_KEY='myungjaMember';
  const SESSION_KEY='myungjaSession';
  function digest(value){var h=2166136261,s='MYUNGJA-local-demo:'+value;for(var i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return (h>>>0).toString(16)}
  function profile(){try{return JSON.parse(localStorage.getItem(PROFILE_KEY)||'null')}catch(e){return null}}
  function session(){try{return JSON.parse(localStorage.getItem(SESSION_KEY)||'null')}catch(e){return null}}
  window.myungjaMember={profile,session,logout:function(){localStorage.removeItem(SESSION_KEY);location.href='index.html'}};
  window.myungjaSignup=function(e){e.preventDefault();const form=e.currentTarget;const email=form.email.value.trim().toLowerCase();const password=form.password.value;const confirm=form.confirmPassword.value;const msg=document.getElementById('formMessage');if(password.length<8){msg.textContent='비밀번호는 8자 이상 입력해 주세요.';return}if(password!==confirm){msg.textContent='비밀번호가 서로 일치하지 않습니다.';return}const member={name:form.memberName.value.trim(),email,phone:form.phone.value.trim(),passwordHash:digest(password),joinedAt:new Date().toISOString()};localStorage.setItem(PROFILE_KEY,JSON.stringify(member));localStorage.setItem(SESSION_KEY,JSON.stringify({email:member.email,name:member.name,loginAt:new Date().toISOString()}));msg.className='form-message success';msg.textContent=member.name+'님, 회원가입이 완료되었습니다.';setTimeout(()=>location.href='account.html',700)};
  window.myungjaLogin=function(e){e.preventDefault();const form=e.currentTarget;const member=profile();const msg=document.getElementById('loginMessage');if(!member){msg.textContent='가입된 계정이 없습니다. 먼저 회원가입을 진행해 주세요.';return}const passwordHash=digest(form.loginPassword.value);if(member.email!==form.loginEmail.value.trim().toLowerCase()||member.passwordHash!==passwordHash){msg.textContent='이메일 또는 비밀번호를 다시 확인해 주세요.';return}localStorage.setItem(SESSION_KEY,JSON.stringify({email:member.email,name:member.name,loginAt:new Date().toISOString()}));msg.className='login-message success';msg.textContent='로그인되었습니다.';setTimeout(()=>location.href='account.html',500)};
  function read(key,fallback){try{return JSON.parse(localStorage.getItem(key)||JSON.stringify(fallback))}catch(e){return fallback}}
  function money(n){return Number(n||0).toLocaleString('ko-KR')+'원'}
  function safe(v){return String(v||'').replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
  function renderAccount(){const member=profile(),active=session(),box=document.getElementById('memberStatus');if(!box)return;if(!(member&&active)){box.innerHTML='<span class="member-kicker">MEMBERSHIP</span><h2>아직 로그인하지 않았습니다</h2><p>회원가입 후 주문 내역과 장바구니를 한곳에서 관리할 수 있습니다.</p><div class="member-actions"><a href="login.html">로그인</a><a href="signup.html">회원가입</a></div>';return}const cart=read('myungjaCart',[]),orders=read('myungjaOrders',[]);const cartTotal=cart.reduce((n,x)=>n+Number(x.price||0)*Number(x.qty||1),0);const cartHtml=cart.length?cart.map(x=>'<a class="account-item" href="'+safe(x.url||'cart.html')+'"><img src="'+safe(x.image)+'" alt=""><div><b>'+safe(x.name)+'</b><span>'+safe(x.color)+' / '+safe(x.size)+' · '+Number(x.qty||1)+'개</span><strong>'+money(Number(x.price||0)*Number(x.qty||1))+'</strong></div></a>').join(''):'<div class="account-empty">장바구니가 비어 있습니다.<br><a href="top.html">상품 둘러보기 →</a></div>';const orderHtml=orders.length?orders.slice().reverse().map(o=>'<article class="account-order"><div class="order-head"><div><span>'+safe(o.date)+'</span><b>주문번호 '+safe(o.id)+'</b></div><em class="status '+(o.status==='취소완료'?'cancelled':'')+'">'+safe(o.status)+'</em></div><div class="order-products">'+(o.items||[]).map(x=>'<div class="account-item"><img src="'+safe(x.image)+'" alt=""><div><b>'+safe(x.name)+'</b><span>'+safe(x.color)+' / '+safe(x.size)+' · '+Number(x.qty||1)+'개</span><strong>'+money(Number(x.price||0)*Number(x.qty||1))+'</strong></div></div>').join('')+'</div><div class="order-foot"><strong>'+money(o.total)+'</strong>'+(o.status!=='취소완료'?'<button type="button" onclick="cancelMyungjaOrder(\''+safe(o.id)+'\')">주문 취소</button>':'<span>취소 처리된 주문입니다</span>')+'</div></article>').join(''):'<div class="account-empty">아직 주문 내역이 없습니다.<br><a href="top.html">첫 상품 만나보기 →</a></div>';box.innerHTML='<section class="profile-summary"><div><span class="member-kicker">WELCOME, '+safe(member.name)+'</span><h2>'+safe(member.name)+'님의 MYUNGJA</h2></div><dl><div><dt>이메일</dt><dd>'+safe(member.email)+'</dd></div><div><dt>휴대전화</dt><dd>'+safe(member.phone)+'</dd></div></dl><button class="member-logout" type="button" onclick="myungjaMember.logout()">로그아웃</button></section><nav class="account-tabs"><a href="#orders">주문·취소 <b>'+orders.length+'</b></a><a href="#savedCart">장바구니 <b>'+cart.reduce((n,x)=>n+Number(x.qty||1),0)+'</b></a></nav><section class="account-section" id="orders"><div class="account-section-head"><div><span>ORDER HISTORY</span><h3>주문 및 취소 내역</h3></div></div>'+orderHtml+'</section><section class="account-section" id="savedCart"><div class="account-section-head"><div><span>SAVED CART</span><h3>장바구니에 담긴 상품</h3></div><div><b>'+money(cartTotal)+'</b><a href="cart.html">장바구니 보기 →</a></div></div><div class="account-cart-grid">'+cartHtml+'</div></section>'}
  window.cancelMyungjaOrder=function(id){const orders=read('myungjaOrders',[]),order=orders.find(x=>x.id===id);if(order){order.status='취소완료';order.cancelledAt=new Date().toISOString();localStorage.setItem('myungjaOrders',JSON.stringify(orders));renderAccount()}}
  window.addEventListener('storage',renderAccount);window.addEventListener('focus',renderAccount);document.addEventListener('DOMContentLoaded',renderAccount);
})();
