(function(){
  function cart(){try{return JSON.parse(localStorage.getItem('myungjaCart')||'[]')}catch(e){return[]}}
  function updateBag(){var count=cart().reduce(function(n,x){return n+(Number(x.qty)||0)},0);document.querySelectorAll('.header-icons').forEach(function(box){var bag=[].slice.call(box.querySelectorAll('span,a')).find(function(x){return /^bag\(/i.test(x.textContent.trim())||x.hasAttribute('data-cart-count')});if(!bag)return;var link=bag.tagName==='A'?bag:document.createElement('a');link.href='cart.html';link.setAttribute('data-cart-count','');link.textContent='bag('+count+')';link.style.color='inherit';link.style.textDecoration='none';if(link!==bag)bag.replaceWith(link)})}
  updateBag();window.addEventListener('storage',updateBag);window.addEventListener('focus',updateBag);
  function updateMember(){var active=null;try{active=JSON.parse(localStorage.getItem('myungjaSession')||'null')}catch(e){}document.querySelectorAll('.header-icons').forEach(function(box){var my=[].slice.call(box.querySelectorAll('span,a')).find(function(x){return x.textContent.trim()==='MY'||x.hasAttribute('data-member-label')});if(!my)return;var link=my.tagName==='A'?my:document.createElement('a');link.href='account.html';link.setAttribute('data-member-label','');link.textContent=active&&active.name?active.name+'님':'MY';if(link!==my)my.replaceWith(link)})}updateMember();window.addEventListener('storage',updateMember);window.addEventListener('focus',updateMember);
  var products=[['시그니처 에어핏 브라탑','TOP 브라탑','product-bra.html','img/signature-airfit-bra.png','62,000원'],['에어리 니트 브라탑','TOP 브라탑','product-airy.html','img/colors/airy-sand-1.png','45,000원'],['브리즈 크롭 반집업','TOP 집업','product-breeze.html','img/colors/breeze-beige-1.png','72,000원'],['쿨터치 슬리브리스','TOP 민소매','product-cool.html','img/colors/cool-black-1.png','39,000원'],['데일리 라운드 반팔티','TOP 반팔','product-daily.html','img/colors/daily-white-1.png','48,000원'],['소프트 저지 캡슬리브 티','TOP 반팔','product-soft.html','img/colors/soft-beige-1.png','42,000원'],['워밍 롱 카디건','TOP 카디건','product-warming.html','img/colors/warming-beige-1.png','98,000원'],['소프트 저지 레깅스','BOTTOM 레깅스','product-leggings.html','img/bottom/leggings-brown-logo-v1.png','68,000원'],['스웨이 온더고 자켓','OUTER 자켓','product-outer-sway.html','img/outer-sway-white-1.png','118,000원']];
  function openSearch(){var modal=document.getElementById('myungjaSearch');if(!modal){modal=document.createElement('div');modal.id='myungjaSearch';modal.className='mj-search';modal.innerHTML='<div class="mj-search-panel"><button class="mj-search-close" type="button" aria-label="검색 닫기">×</button><span>SEARCH MYUNGJA</span><div class="mj-search-input"><input type="search" placeholder="찾고 싶은 상품명을 입력하세요" aria-label="상품 검색"><button type="button">검색</button></div><div class="mj-search-result"></div></div>';document.body.appendChild(modal);var input=modal.querySelector('input'),result=modal.querySelector('.mj-search-result');function search(){var q=input.value.trim().toLowerCase(),hits=products.filter(p=>!q||p[0].toLowerCase().includes(q)||p[1].toLowerCase().includes(q));result.innerHTML=hits.length?hits.map(p=>'<a href="'+p[2]+'"><img src="'+p[3]+'" alt=""><div><span>'+p[1]+'</span><b>'+p[0]+'</b><em>'+p[4]+'</em></div></a>').join(''):'<p>검색 결과가 없습니다. 다른 상품명이나 카테고리를 입력해 보세요.</p>'}modal.querySelector('.mj-search-close').onclick=()=>{modal.classList.remove('open');document.body.style.overflow=''};modal.querySelector('.mj-search-input button').onclick=search;input.oninput=search;input.onkeydown=e=>{if(e.key==='Enter')search()};search()}modal.classList.add('open');document.body.style.overflow='hidden';setTimeout(()=>modal.querySelector('input').focus(),30)}
  document.querySelectorAll('.header-icons').forEach(function(box){var search=[].slice.call(box.querySelectorAll('span,a,button')).find(x=>x.textContent.trim()==='검색');if(search){var button=search.tagName==='BUTTON'?search:document.createElement('button');button.type='button';button.className='mj-search-trigger';button.textContent='검색';button.setAttribute('aria-label','상품 검색 열기');button.onclick=openSearch;if(button!==search)search.replaceWith(button)}});document.addEventListener('keydown',e=>{if(e.key==='Escape'){var m=document.getElementById('myungjaSearch');if(m&&m.classList.contains('open')){m.classList.remove('open');document.body.style.overflow=''}}});
  document.querySelectorAll('.category-toolbar [data-filter]').forEach(function(button){button.addEventListener('click',function(){var value=button.dataset.filter;var toolbar=button.closest('.category-toolbar');toolbar.querySelectorAll('[data-filter]').forEach(function(x){x.classList.toggle('active',x===button)});var scope=toolbar.parentElement;var cards=scope.querySelectorAll('[data-category]');var visible=0;cards.forEach(function(card){var show=value==='전체'||card.dataset.category===value;card.style.setProperty('display',show?'block':'none','important');if(show)visible++});var count=scope.querySelector('.title>span,.product-count');if(count){var unit=scope.classList.contains('set-category')?'개 세트':'개 상품';count.textContent=(value==='전체'?'전체 ':value+' ')+visible+unit}})});
})();
